controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

mecanum_drive_controller:
  ros__parameters:
    use_stamped_vel: false # Important pour teleop simple
    base_frame_id: "chassis"
    odom_frame_id: "odom"
    enable_odom_tf: true
    
    # Noms des joints (Doivent correspondre EXACTEMENT au URDF)
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"

    # Paramètres cinématiques (LA CORRECTION EST ICI)
    kinematics:
      base_frame_offset: {x: 0.0, y: 0.0, theta: 0.0}
      wheels_radius: 0.04
      # C'est la somme de (largeur/2 + longueur/2). 
      # Votre robot: width=0.12, length=0.12 (entre roues).
      # Donc (0.06 + 0.06) = 0.12
      sum_of_robot_center_projection_on_X_Y_axis: 0.12

    reference_timeout: 1.0